version: "3.4"

x-default: &default 
  restart: always
  networks:
    - im_service
  volumes: 
    - ./tmp:/app/tmp

services:
  ims_1:
    build: 
      context: .
      dockerfile: service.dockerfile
    entrypoint: ["/app/ims", "ims.cfg"]
    <<: *default
  ims_2:
    build:
      context: .
      dockerfile: service.dockerfile
    entrypoint: [ "/app/ims", "ims.cfg" ]
    <<: *default
  imr_1:
    build: 
      context: .
      dockerfile: service.dockerfile
    entrypoint: ["/app/imr", "imr.cfg"]
    <<: *default
  imr_2:
    build:
      context: .
      dockerfile: service.dockerfile
    entrypoint: [ "/app/imr", "imr.cfg" ]
    <<: *default
  im:
    build: 
      context: .
      dockerfile: service.dockerfile
    entrypoint: ["/app/im", "im.cfg"]
    ports:
      - "24430:24430"
      - "23000:23000"
      - "14891:14891"
      - "13891:13891"
      - "6666:6666"
      - "6665:6665"
    depends_on:
      - ims_1
      - ims_2
      - imr_1
      - imr_2
    <<: *default
networks:
  im_service:
